# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\x06vision\x1a\x1bgoogle/protobuf/empty.proto\":\n\nBackground\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\r\n\x05\x63olor\x18\x03 \x03(\r\"X\n\x04Line\x12\n\n\x02xs\x18\x01 \x01(\x02\x12\n\n\x02ys\x18\x02 \x01(\x02\x12\n\n\x02xe\x18\x03 \x01(\x02\x12\n\n\x02ye\x18\x04 \x01(\x02\x12\r\n\x05\x63olor\x18\x05 \x03(\r\x12\x11\n\tlineWidth\x18\x06 \x01(\r\"Y\n\x06\x43ircle\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01r\x18\x03 \x01(\x02\x12\r\n\x05\x63olor\x18\x04 \x03(\r\x12\x11\n\tlineWidth\x18\x05 \x01(\r\x12\x0c\n\x04\x66ill\x18\x06 \x01(\x08\"d\n\x04Rect\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\n\n\x02rx\x18\x03 \x01(\x02\x12\n\n\x02ry\x18\x04 \x01(\x02\x12\r\n\x05\x63olor\x18\x05 \x03(\r\x12\x11\n\tlineWidth\x18\x06 \x01(\r\x12\x0c\n\x04\x66ill\x18\x07 \x01(\x08\"X\n\x07Polygon\x12%\n\x06points\x18\x01 \x03(\x0b\x32\x15.vision.Polygon.Point\x12\r\n\x05\x63olor\x18\x02 \x03(\r\x1a\x17\n\x05Point\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x19\n\x08Response\x12\r\n\x05state\x18\x01 \x01(\x08\x32\xa8\x02\n\x11VisionRendererAPI\x12\x31\n\x07refresh\x12\x12.vision.Background\x1a\x10.vision.Response\"\x00\x12(\n\x04line\x12\x0c.vision.Line\x1a\x10.vision.Response\"\x00\x12,\n\x06\x63ircle\x12\x0e.vision.Circle\x1a\x10.vision.Response\"\x00\x12(\n\x04rect\x12\x0c.vision.Rect\x1a\x10.vision.Response\"\x00\x12.\n\x08polyline\x12\x0c.vision.Line\x1a\x10.vision.Response\"\x00(\x01\x12.\n\x07polygon\x12\x0f.vision.Polygon\x1a\x10.vision.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKGROUND._serialized_start=53
  _BACKGROUND._serialized_end=111
  _LINE._serialized_start=113
  _LINE._serialized_end=201
  _CIRCLE._serialized_start=203
  _CIRCLE._serialized_end=292
  _RECT._serialized_start=294
  _RECT._serialized_end=394
  _POLYGON._serialized_start=396
  _POLYGON._serialized_end=484
  _POLYGON_POINT._serialized_start=461
  _POLYGON_POINT._serialized_end=484
  _RESPONSE._serialized_start=486
  _RESPONSE._serialized_end=511
  _VISIONRENDERERAPI._serialized_start=514
  _VISIONRENDERERAPI._serialized_end=810
# @@protoc_insertion_point(module_scope)
